### ISSUE TITLE
Rename repo to tokens-list

### ISSUE THREAD

**Issue by nop33** [alephium/token-list#6]
@mvaivre @tdroxler WDYT? The "meta" is too meta :P

Our NPM package could be named `@alephium/tokens-list`

**Comment by tdroxler** [comment]
Before closing this one we need to fix this test https://github.com/alephium/token-list/blob/70645ea13b2ff431d341daca20135dcb51559b1b/test/token-list/token-list.test.ts#L46 and also all images in our *.json file
